# Generated by Django 5.1.7 on 2025-03-28 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_estudio', models.DateField()),
                ('sede', models.CharField(max_length=100)),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Media', max_length=5)),
                ('imagen', models.BinaryField(blank=True, null=True)),
                ('checklist_causas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checklists.checklistcausas')),
                ('checklist_emergencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checklists.checklistemergencia')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
            options={
                'verbose_name_plural': 'Estudios',
            },
        ),
    ]
