# Generated by Django 5.1.7 on 2025-03-29 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0002_remove_estudio_imagen_estudio_ruta_archivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudio',
            old_name='paciente',
            new_name='paciente_id',
        ),
    ]
