# Generated by Django 5.1.7 on 2025-03-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('nss', models.CharField(max_length=11, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Pacientes',
            },
        ),
    ]
