# Generated by Django 5.1.7 on 2025-03-28 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistCausas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traumatismo_cabeza', models.BooleanField(default=False)),
                ('presion_alta', models.BooleanField(default=False)),
                ('colesterol_alto', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('antecedentes_familiares', models.BooleanField(default=False)),
                ('enfermedad_cardiovascular', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
            options={
                'verbose_name_plural': 'Checklists de Causas',
            },
        ),
        migrations.CreateModel(
            name='ChecklistEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificultad_hablar', models.BooleanField(default=False)),
                ('entumecimiento_cara', models.BooleanField(default=False)),
                ('entumecimiento_brazo', models.BooleanField(default=False)),
                ('problemas_ver', models.BooleanField(default=False)),
                ('dolor_cabeza', models.BooleanField(default=False)),
                ('problemas_caminar', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
            options={
                'verbose_name_plural': 'Checklists de Emergencia',
            },
        ),
    ]
