# Generated by Django 5.1.7 on 2025-03-29 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_rename_paciente_checklistcausas_paciente_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistemergencia',
            old_name='paciente',
            new_name='paciente_id',
        ),
    ]
