# Generated by Django 5.1.7 on 2025-03-28 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_estudio', models.DateField()),
                ('fecha_resultado', models.DateField()),
                ('estado_estudio', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Finalizado', 'Finalizado')], max_length=10)),
                ('prediccion_ia', models.CharField(choices=[('Poco probable', 'Poco probable'), ('Probable', 'Probable'), ('Muy probable', 'Muy probable')], max_length=13)),
                ('precision', models.CharField(max_length=50)),
                ('imagen_estudio', models.BinaryField(blank=True, null=True)),
                ('resumen_prediccion', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
            options={
                'verbose_name_plural': 'Resultados',
            },
        ),
    ]
