# Generated by Django 5.1.7 on 2025-03-30 23:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        ('resultados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultado',
            options={'ordering': ['-fecha_estudio', '-creado_en'], 'verbose_name': 'Resultado', 'verbose_name_plural': 'Resultados'},
        ),
        migrations.AddField(
            model_name='resultado',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultado',
            name='estado_estudio',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=20, verbose_name='Estado del estudio'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='fecha_estudio',
            field=models.DateField(verbose_name='Fecha del estudio'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='fecha_resultado',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha del resultado'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='imagen_estudio',
            field=models.ImageField(blank=True, null=True, upload_to='resultados/imagenes/', verbose_name='Imagen de referencia'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='pacientes.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='precision',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precisión (%)'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='prediccion_ia',
            field=models.CharField(choices=[('Poco probable', 'Poco probable'), ('Probable', 'Probable'), ('Muy probable', 'Muy probable')], max_length=15, verbose_name='Predicción de IA'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='resumen_prediccion',
            field=models.TextField(blank=True, null=True, verbose_name='Resumen de la predicción'),
        ),
        migrations.AddIndex(
            model_name='resultado',
            index=models.Index(fields=['fecha_estudio'], name='resultados__fecha_e_15d780_idx'),
        ),
        migrations.AddIndex(
            model_name='resultado',
            index=models.Index(fields=['estado_estudio'], name='resultados__estado__b3750e_idx'),
        ),
        migrations.AddIndex(
            model_name='resultado',
            index=models.Index(fields=['prediccion_ia'], name='resultados__predicc_bc25de_idx'),
        ),
    ]
