# Generated by Django 5.1.7 on 2025-04-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0002_alter_resultado_options_resultado_actualizado_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='imagen_estudio',
            field=models.FileField(blank=True, null=True, upload_to='resultados/imagenes/', verbose_name='Imagen de referencia'),
        ),
    ]
