# Generated by Django 5.1.7 on 2025-04-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0003_alter_resultado_imagen_estudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='probabilidades',
            field=models.TextField(blank=True, null=True, verbose_name='Probabilidades de predicción (JSON)'),
        ),
    ]
